version: '3.8'

services:
  mssql:
    build:
        context: ./mssql
        dockerfile: Dockerfile
    container_name: mssql_server_dev
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=nhomNaymuoidiem!
      - MSSQL_PID=Developer
    ports:
      - "1435:1433"
    volumes:
      - sql_data:/var/opt/mssql
       - ./mssql/backup:/var/opt/mssql/backup
      
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "sqlcmd -S localhost -U sa -P 'nhomNaymuoidiem!' -Q 'SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s 
  
  backend:
    container_name: backend_server
    platform: linux/amd64
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    environment:
      - DB_HOST=host.docker.internal
    depends_on:
      mssql:
        condition: service_healthy
    ports:
      - 3030:3030

  nginx:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:80

volumes:
  sql_data:
    driver: local


